#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Alarm.Resource", IsApplication=true)]

namespace Alarm
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_right_Timepicker = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_up_Timepicker = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int theme_devicedefault_background = 2131296256;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cbchk_daypicker = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cbchk_daypicker2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cbunchk_daypicker = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cbunchk_daypicker2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Daypicker_checkbox = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int trash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int action_radio_button = 2131361792;
			
			// aapt resource value: 0x7f0a0018
			public const int actionpicker_button_cancel = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int actionpicker_button_save = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int actionpicker_listview = 2131361815;
			
			// aapt resource value: 0x7f0a0020
			public const int add_alarm_button = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int alarm_listview = 2131361825;
			
			// aapt resource value: 0x7f0a0010
			public const int alarm_settings_action = 2131361808;
			
			// aapt resource value: 0x7f0a0006
			public const int alarm_settings_button_delete = 2131361798;
			
			// aapt resource value: 0x7f0a0016
			public const int alarm_settings_button_save = 2131361814;
			
			// aapt resource value: 0x7f0a0015
			public const int alarm_settings_duration = 2131361813;
			
			// aapt resource value: 0x7f0a0014
			public const int alarm_settings_snooze_time = 2131361812;
			
			// aapt resource value: 0x7f0a0007
			public const int alarm_settings_time = 2131361799;
			
			// aapt resource value: 0x7f0a0012
			public const int alarm_settings_volume_label = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int alarm_settings_volume_slider = 2131361811;
			
			// aapt resource value: 0x7f0a0005
			public const int alarm_time = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int alarm_toggle = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int alarmgoingoff_off = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int alarmgoingoff_snooze = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int alarmgoingoff_time = 2131361793;
			
			// aapt resource value: 0x7f0a000d
			public const int daypicker_friday = 2131361805;
			
			// aapt resource value: 0x7f0a0009
			public const int daypicker_monday = 2131361801;
			
			// aapt resource value: 0x7f0a000e
			public const int daypicker_saturday = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int daypicker_sunday = 2131361807;
			
			// aapt resource value: 0x7f0a000c
			public const int daypicker_thursday = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int daypicker_tuesday = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int daypicker_wednesday = 2131361803;
			
			// aapt resource value: 0x7f0a0008
			public const int linearLayout1 = 2131361800;
			
			// aapt resource value: 0x7f0a0011
			public const int linearLayout2 = 2131361809;
			
			// aapt resource value: 0x7f0a001a
			public const int numberpicker = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int numberpicker_button_cancel = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int numberpicker_button_save = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int timepicker = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int timepicker_button_cancel = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int timepicker_button_save = 2131361823;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ActionListView_row = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AlarmGoingOff = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AlarmListView_row = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AlarmSettings = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int DialogActionpicker = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int DialogNumberPicker = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int DialogTimepicker = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Main = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int alarm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int chopin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int prettypimpin = 2131099649;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int add_alarm = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cancel = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int duration = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int fridayAbr = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int mondayAbr = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int saturdayAbr = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int save = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int snooze = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int snoozeTime = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int sundayAbr = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int thursdayAbr = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int tuesdayAbr = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int turnOff = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int volume = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int wednesdayAbr = 2131165195;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Mono_Android_Theme_Splash = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Theme_Custom = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int timepicker_animation = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
